### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by pitkz** [MiltonBalaOfficial/IncreaseAndDecreasePageDimensions#1]
Hey Milton,

thank you for your fast action! I really appreciate your effort.

Some quick Question:

Your Readme states

> Place the icons () in:
> 
>     C:\Users\<user>\AppData\Local\share\icons\hicolor\scalable\actions on Windows,
>     ~/.local/share/icons/hicolor/scalable/actions/ on Linux or MacOS

Which Icons? I didnt see any available for download, or, which IconNames to use as checking your IncreasePageSize.lua file didnt gave me any info which iconnames are called?

I would appreciate if you could add some icons so its easy for me non-dev to simply copy/paste your git, and by that make it easy for alot of folks I would recommend your Plugin to.

**Priority to me: High**

Thanks

PS: Please add some donation button into Git :)

**Comment by MiltonBalaOfficial** [comment]
Let me allow some time, I definitely want to help you.

**Comment by MiltonBalaOfficial** [comment]
Is the plugin working on your system?

**Comment by pitkz** [comment]
Yep! Runs flawlessly on Linux with the older X++ 1.2.2 (via Ubuntu PPA) as you can see here:
https://github.com/MiltonBalaOfficial/IncreaseAndDecreasePageDimensions/issues/2

**Comment by MiltonBalaOfficial** [comment]
Icons have been provided. Let me know if it works or not.

**Comment by 6xthFNGR** [comment]
Thank you, the icons run with X++ 1.2.2 and on Linux with the locations you advised! I guess this ticket can be closed.

**Comment by pitkz** [comment]
Thank you, the icons run with X++ 1.2.2 and on Linux with the locations you advised! I guess this ticket can be closed.

**Comment by pitkz** [comment]
Hey,

due to Ubuntu PPA only offering X++ 1.2.2 I was considering to use Snapcraft (snap) installation which allows for newer 1.2.4 builds with the "edge" channel, with the nice additional feature of sandboxing X++ and while still having updates comfortably managed by the system/snap instead of using the .deb file by github and needing to manually update everytime.

But due to snap sandbox, some critical folders are not accessible and mounted as read-only.

I do have write privileges to the "simulated" Plugin folder ( ~/snap/xournalpp/100/.config/xournalpp/plugins )
but X++ (snap) and the Plugins can not access the native ( ~/.local/share/icons/hicolor/scalable/ ) folder where the Icons belong,
neither do I as user/superuser have write privileges to anything beyond ~/snap/xournalpp/100/.local/share/icons. Dont ask me why the policy is to grant access to ~/snap/xournalpp/100/.config but not ~/snap/xournalpp/100/.local/share/icons/

While X++ (snap) can access native home directory ( ~/ ), it cannot access hidden folders within that for security reasons (hidden folder = DOT Foldername, e.g. ".local")
One workaround on my side would be to create messy duplications of the icons folders or create additional empty folders and use symlink, but I rather want to keep everything contained and not clutter my ~/ (home) directory

---

Proposed solution:
Would it be possible to make an extension to the page_adjust_config.lua or plugin.ini and let the user specify an alternative path by his own for the case of using snaps, and include a short description to the readme?

In this case I would like to try placing your icons simply within a new icon directory I create in your plugin folder as I have write priviliges for it ( ~/snap/xournalpp/100/.config/xournalpp/plugins/IncreaseAndDecreasePageDimensions -> creating "icon" subdirectory)

Just as a side node,  if you are interested:
" ~ /snap/xournalpp " is the folder where everything a snap package includes is stored.
"100" is the simulated user name and therefor the fake home directory (~/ or /home/100). Anything beyond that is the common folder hierarchy with some of them mounted as read-only with no possibility to overcome this.

By the way: If anyone asks you to provide help for flatpak, deny it :) Flatpak is dangerous and bad.

Thanks!

**Comment by MiltonBalaOfficial** [comment]
I don't know if it is possible or not, it is beyond my knowledge, would you please consider asking on Xournal repository by mentioning [rolandlo] (https://github.com/rolandlo), he might have an answer. 

@Robin-Sch , would you suggest any answer?


> By the way: If anyone asks you to provide help for flatpak, deny it :) Flatpak is dangerous and bad.

Thanks

**Comment by Robin-Sch** [comment]
The icons have to be put in any "hicolor" compatible folder. I am not using snap myself, but if I am not mistaken there is also a `/usr/share/icons/hicolor` folder, maybe try that (also in this case put it the `scalable/actions` subdir)

**Comment by pitkz** [comment]
Hey,

@Robin-Sch
The path "/usr/" and and therefor /usr/share/icons/hicolor/scalable/actions" is not accessible by snaps due to security restrictions. I think you can connect (sudo snap connect xournalpp:usr) or smth like that, but than you are giving up the sandbox feature and allow X++ to alter system critical directories.
Containing everything in /home/ is neat and clean.

@MiltonBalaOfficial

    I don't know if it is possible or not

Perhaps my question wasn’t clear: Instead of calling the icon without a path, could we allow users to set a custom path manually?

For example:
Currently, we use something like this:

`{menu = "Increase Bottom", callback = "increaseSizeDown", accelerator = "<Alt>4", toolbarId = "increaseSizeDown", iconName = "IncreaseDimBottom"}`

What I’m proposing is:

`{menu = "Increase Bottom", callback = "increaseSizeDown", accelerator = "<Alt>4", toolbarId = "increaseSizeDown", iconName = "IncreaseDimBottomFeature"}`

Additionally, some code could define the behavior:
If IconPathFeature in page_adjust_config.lua is set to 0, the plugin uses the default "IncreaseDimBottom". Otherwise, it uses a custom path, such as "IconPath/IconName", where IconPath would be user-defined (e.g., ./icons/).


Below is a potential implementation for the idea in Lua made by ChatGPT 4o 

```
-- Load user configuration (example for page_adjust_config.lua)
local config = require("page_adjust_config") -- Ensure config contains 'IconPathFeature' and 'IconPath'

-- Function to resolve the icon path
local function resolveIconPath(iconName)
    if config.IconPathFeature == 0 then
        -- Default system path
        return iconName
    else
        -- User-defined path
        return config.IconPath .. iconName .. ".svg"
    end
end

-- Define actions with dynamic icon paths
local actions = {
    {
        menu = "Increase Bottom",
        callback = "increaseSizeDown",
        accelerator = "<Alt>4",
        toolbarId = "increaseSizeDown",
        iconName = resolveIconPath("IncreaseDimBottom")
    },
    {
        menu = "Decrease Bottom",
        callback = "decreaseSizeDown",
        accelerator = "<Alt>5",
        toolbarId = "decreaseSizeDown",
        iconName = resolveIconPath("DecreaseDimBottom")
    }
}

-- Register actions dynamically
for _, action in ipairs(actions) do
    app.registerUi(action)
end
```

Example Configuration File (page_adjust_config.lua):

```
return {
    IconPathFeature = 1, -- 0: Use system icons, 1: Use custom icons
    IconPath = "./icons/" -- Path to custom icons (must end with '/')
}
```

What do you think?
I dont want to clutter your code with this usercase of using snap so Im fine if thats bothering you.
Yet, if it works, the advantage would be that your plugin becomes "systemless": No matter which OS like windows, mac, linux, android, freebsd and no matter if using snaps, flatpak or whateve: the user nor you ever have to care for icon directory's as everything is contained within your plugin directory.

**Comment by MiltonBalaOfficial** [comment]
Now your question is clear to me. Let me allow some time (A couple of days, as I am off the town) to do some research and consult the developers of X++.

**Comment by MiltonBalaOfficial** [comment]
I have tried some different methods, but didn't work. I also asked a question about this in x+ repository, just now I have got a reply that it is not possible through a plugin. The reply: https://github.com/xournalpp/xournalpp/discussions/6114#discussioncomment-11444095

**Comment by pitkz** [comment]
Thank you for your effort - too bad.

Cheers
