### ISSUE TITLE
Feature Request: Apply to all pages

### ISSUE THREAD

**Issue by pitkz** [MiltonBalaOfficial/IncreaseAndDecreasePageDimensions#4]
Hey,

may I ask you to add a line/shortcut to extend the page dimensions of all pages at once, so I save myself alot of time?
That would be great!

BTW: After the first test and the 4 tickets I opened, I think Im quite happy with where your Plugin is going and I can not think of too many more things to ask before using it in a production environment and recommending it to my department.

**Priority to me: High**

Thank you alot for this already.

PS: Please add some donation button into Git :)

**Comment by MiltonBalaOfficial** [comment]
Functionality have been added. If you want to support, link is provided in `README`

**Comment by pitkz** [comment]
Thank you, Ive tested it and the features do run with X++ 1.2.2! Thank you for your very fast response. I guess this ticket can be closed.
