### ISSUE TITLE
Reviewed Code by ChatGPT 4o and Question regarding "pt" vs. "cm" Scale.

### ISSUE THREAD

**Issue by pitkz** [MiltonBalaOfficial/IncreaseAndDecreasePageDimensions#6]
Hey Milton,

Im not a dev, but Ive quickly asked ChatGPT 4o to review your code. I can not really interpret the reply by ChatGPT but maybe it helps you?
Additionally I added a personal note for Point 4 regarding "pt" and "cm" dimensions.
 

**Summary of Changes and Justifications**

**1. Clearer Comments**
What changed: Comments were rewritten to better explain the purpose of each function and parameter.
Why: Precise and clear comments improve the readability and maintainability of the code, especially for future modifications or other developers working on it.

**Original:**
> -- Helper function to adjust page size

**Improved:**
>     -- Helper function to adjust the size of pages in the document
>     -- @param amountWidth: Change in page width
>     -- @param amountHeight: Change in page height
>     -- @param forAllPages: If true, apply the change to all pages; otherwise, only the current page

---

_2. Consistent and Descriptive Variable Names_
_What changed: Variables were renamed to maintain consistency and better describe their purpose (e.g., docStructure instead of ambiguous terms like doc).
Why: Consistency in naming conventions makes the code easier to follow and reduces confusion._

Original:_
`local docStructure = app.getDocumentStructure()`
_No major change, but consistency maintained._

--> Seems like ChatGPT bullcrap. Your original variable name was already docStructure.

---

**3. Error Prevention: Page List Validation**
What changed: Added validation to ensure the page list is not empty before processing.
Why: Prevents runtime errors or crashes if the docStructure["pages"] is empty or malformed.

**Added Code:**

```
    if not pages or #pages == 0 then
        print("No pages found to adjust.")
        return
    end
```

---

**4. Step Size Centralization**
What changed: Replaced hardcoded values (71) with a global variable for the adjustment step size.
Why: Centralizing the step size in a variable makes it easier to adjust in the future without modifying multiple lines of code.

**Original:**

`function increaseSizeRight() adjustPageSize(71, 0, false) end`

Improved:

```
    local adjustmentStep = 71 -- Global step size for adjustments

    function increaseSizeRight() adjustPageSize(adjustmentStep, 0, false) end
```

**---> Personal note by me (human):**
I wonder if its the right decision to use 71pt instead of 2.5cm?
With _X++ -> Preferences -> Zoom_ the user "calibrates" the actual scale to his monitor, so may I ask if 71pt will than be displayed different on different monitors while 2.5cm stays consistent on every monitor due to the calibration in X++, or is "pt" the better dimension to use for staying consistent across multiple plattforms?

---

**5. Improved Logic for Page Selection**
What changed: Clarified the logic for selecting pages to process by splitting it into clear conditions.
Why: This makes the function easier to understand and debug.

**Original:**

`local pages = forAllPages and docStructure["pages"] or {docStructure["pages"][docStructure["currentPage"]]}`

**Improved:**

```
    -- Determine which pages to process
    local pages
    if forAllPages then
        pages = docStructure["pages"] -- All pages
    else
        pages = {docStructure["pages"][docStructure["currentPage"]]} -- Current page only
    end
```

---

**6. Simplified Action Registration**
What changed: Grouped actions into a loop with less redundancy and more clarity.
Why: Simplifies action registration and makes the code cleaner and easier to expand.

**Original:**

```
local actions = {
    {menu="Increase Right", callback="increaseSizeRight", accelerator="<Alt>2", toolbarId="increaseSizeRight", iconName="IncreaseDimRight"},
    {menu="Decrease Right", callback="decreaseSizeRight", accelerator="<Alt>3", toolbarId="decreaseSizeRight", iconName="DecreaseDimRight"},
    ...
}
```

Improved:

```
    local actions = {
        {menu="Increase Right", callback="increaseSizeRight", accelerator="<Alt>2", toolbarId="increaseSizeRight", iconName="IncreaseDimRight"},
        {menu="Decrease Right", callback="decreaseSizeRight", accelerator="<Alt>3", toolbarId="decreaseSizeRight", iconName="DecreaseDimRight"},
        {menu="Increase Bottom", callback="increaseSizeDown", accelerator="<Alt>4", toolbarId="increaseSizeDown", iconName="IncreaseDimBottom"},
        {menu="Decrease Bottom", callback="decreaseSizeDown", accelerator="<Alt>5", toolbarId="decreaseSizeDown", iconName="DecreaseDimDown"},
        ...
    }

    -- Register UI actions
    for _, action in ipairs(actions) do
        app.registerUi(action)
    end
```

---

**7. Optional: Tooltip Support**
What changed: Added a suggestion to include tooltips for better usability.
Why: If app.registerUi supports tooltips, this can enhance the user experience by providing quick explanations for each action.

Key Benefits of These Changes

    Improved Readability: The code is now easier to read and understand, even for developers unfamiliar with the project.
    Enhanced Maintainability: Centralized variables (like step size) and better logic make future updates simpler.
    Error Handling: Validating inputs prevents crashes or unexpected behavior.
    Scalability: Modular design and action grouping make the code easier to extend or modify.

Next Steps for the Developer

    Review the added error-checking mechanism for page list validation.
    Consider centralizing more parameters (e.g., accelerators) if they’re likely to change.
    Test whether tooltips can be incorporated for actions in app.registerUi.
    Verify if the centralized step size aligns with the intended user flexibility.

**Comment by MiltonBalaOfficial** [comment]
Its great that you put your time on it. Lets describe the actual scenario, I am not also a developer. When I started using `Xournal++` I felt the need of many features. I used to request features from the deveoper of Xournal++, some of them were closed by them as `not planned`, `duplication`, `you can make your own plugins` etc. 

But I didn't know anything about C, C+ or lua. I learnt only HTML and CSS in my school days! But I cannot ignore the need of some plugins for my notemaking purpose, so I have learnt a little bit lua to make some "Just working plugin" for my needs. 

When I saw your feature request on Xournalapp repository, I already knew the reply of the devoloper beforehand. So, I just upload the plugin for you with minimal modification to help you according to my ability. When you request for features here, I tried to help you as my ability.

But I will try to upgrade this plugin by implementing your points. If you have already upgraded it, you may share with us.
Thank you.

**Comment by Robin-Sch** [comment]
Should you need some help, feel free to ping me and I'll help wherever I can!

**Comment by MiltonBalaOfficial** [comment]
> Summary of Changes and Justifications

Some changes have been done. Now you can increase/decrease by cm or even by percentage of the current page dimensions, the  width or height can be doubled by just a click! Let me know your review. (There are some code duplication, I will work on it later)

**Comment by MiltonBalaOfficial** [comment]
If you are satisfied with the changes please close the issue. ( I personally don't like to close the issue until the issue raiser is convinced.)

**Comment by pitkz** [comment]
> Some changes have been done. Now you can increase/decrease by cm or even by percentage of the current page dimensions, the width or height can be doubled by just a click! Let me know your review. (There are some code duplication, I will work on it later)

Hello Milton!
Thank you so much for your work on this.

I really like the option to adjust dimensions by percentage—it’s a great addition! While 100% might be a bit much for my personal preference, I appreciate that I can easily modify this in the .lua files myself.

I also love that you’ve structured it so that users can simply edit the page_adjust_config.lua file without needing to touch ChangePageDimension.lua. This is a thoughtful design choice that makes the feature much more user-friendly.

**--> one minor feedback** would be to maybe stay consistent in name schemes and never user upper case letters while using dashes for seperating words (like page_adjust_config.lua) or to always use uppercase letters but never use dashes (like ChangePageDimension.lua). But thats nothing too serious!

Regarding the ChatGPT feedback, I can’t personally judge whether all the suggestions were valid or how well you incorporated or surpassed them. My intent was just to give you some additional ideas, and I think developers like Robin are in a better position to provide you with more technical feedback.

That said, I’m grateful that some of the feedback was useful for you to some degree!

Thanks again for your effort—I truly appreciate it!
